### PR TITLE
Adding AWD

### PR DESCRIPTION
**Pull request by aarongustafson**

### CODE REVIEW

**Comment by aarongustafson** [comment]
I want to organize things a little more, but I’m not sure the best way. Alphabetically is probably easiest, but subject might be helpful too.

**Review by antoinentl — APPROVED** [review]

**Comment by antoinentl** [comment]
I'd like to keep a chronologically organisation, but I understand your motivation. I prefer to keep this order until there are not too many titles, ok for you?

**Comment by aarongustafson** [comment]
Fine with me. I can move my book around if you want. The order wasn’t clear
to me :-)

**Comment by antoinentl** [comment]
Yes you can, thanks!

**Pull request merged**
